version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: dndsys-db
    environment:
      POSTGRES_DB: dndsys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
